-- =====================================================================
-- prod-missing-2026-08-03.sql
-- Objects present in DEV (local postgres@5433) but MISSING in PROD,
-- generated by diffing the prod snapshot (data-1785689205410.csv,
-- taken 2026-08-03) against the live dev catalog.
--
-- Contents (everything is guarded / idempotent — safe to re-run):
--   1. ref_country seed row 'AE' (required by the new FKs/defaults)
--   2. New table  : ecom_flat_fee (+ sequence, PK, unique index, FK)
--   3. New columns: country_code / cap_currency_code / home_country_code
--                   on interchange_rate_local, mcc_sector_map,
--                   scheme_fee_rate, tenant
--   4. New indexes on those tables
--   5. New FKs to ref_country
--   6. Definition changes (from the deep definition diff):
--      - tenant_id becomes NULLABLE on interchange_rate_local,
--        mcc_sector_map, scheme_fee_rate (country-level default rows
--        use tenant_id NULL — see COALESCE(tenant_id,0) unique keys)
--      - old unique keys replaced by country-aware ones:
--        mcc_sector_map_tenant_id_mcc_key  → uq_mcc_sector_map_key
--        uq_scheme_fee_rate_key (old def)  → uq_scheme_fee_rate_key (new def)
--      - users.email: NOT NULL dropped and unique uq_users_email dropped
--        (dev keeps username as the unique login key)
--
-- Deliberately EXCLUDED:
--   - flyway_schema_history: Flyway's own bookkeeping table. Never create
--     it by hand — Flyway creates and manages it when it first runs.
--   - email_smtp_config (+ its indexes): exists only in prod, dev dropped
--     it (superseded by email_config). Dropping it is destructive and may
--     hold live SMTP credentials — decide separately.
--   - Prod-only extras left alone: fact_transaction perf indexes
--     (idx_fact_txn_card, idx_fact_transaction_tenant_merchant_date),
--     bigint sequences where dev uses integer (harmless), and CHECK
--     constraint text differences (PG16 vs PG18 pretty-printing only).
--
-- Review before running. Run in one go:
--   psql -h <prod-endpoint> -p 5432 -U <user> -d <db> -f prod-missing-2026-08-03.sql
-- =====================================================================

BEGIN;

-- ── 1. Seed the 'AE' country row ─────────────────────────────────────
-- The new NOT NULL columns default to 'AE' and are FK'd to ref_country,
-- so this row must exist BEFORE the columns/FKs are added.
INSERT INTO public.ref_country (country_code, country_name, currency_code, currency_name, currency_symbol, phone_code, iso_numeric, decimal_notation_value)
VALUES ('AE', 'UNITED ARAB EMIRATES', 'AED', 'Dirham', 'AED', '971', '784', 100)
ON CONFLICT (country_code) DO NOTHING;

-- ── 2. ecom_flat_fee (new table) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.ecom_flat_fee (
    id bigint NOT NULL,
    tenant_id integer,
    country_code character varying(2) NOT NULL,
    fee_amount numeric(19,4) NOT NULL,
    label character varying(80)
);

CREATE SEQUENCE IF NOT EXISTS public.ecom_flat_fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.ecom_flat_fee_id_seq OWNED BY public.ecom_flat_fee.id;

ALTER TABLE ONLY public.ecom_flat_fee ALTER COLUMN id SET DEFAULT nextval('public.ecom_flat_fee_id_seq'::regclass);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'ecom_flat_fee_pkey'
                     AND conrelid = 'public.ecom_flat_fee'::regclass) THEN
        ALTER TABLE ONLY public.ecom_flat_fee
            ADD CONSTRAINT ecom_flat_fee_pkey PRIMARY KEY (id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_ecom_flat_fee_key
    ON public.ecom_flat_fee USING btree (country_code, COALESCE(tenant_id, 0));

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_ecom_flat_fee_country'
                     AND conrelid = 'public.ecom_flat_fee'::regclass) THEN
        ALTER TABLE ONLY public.ecom_flat_fee
            ADD CONSTRAINT fk_ecom_flat_fee_country
            FOREIGN KEY (country_code) REFERENCES public.ref_country(country_code);
    END IF;
END $$;

-- ── 3. Missing columns ───────────────────────────────────────────────
-- NOT NULL DEFAULT 'AE'/'AED' backfills every existing prod row with the
-- default (fast metadata-only operation on PG11+, no table rewrite).
ALTER TABLE public.interchange_rate_local
    ADD COLUMN IF NOT EXISTS country_code      character varying(2) NOT NULL DEFAULT 'AE',
    ADD COLUMN IF NOT EXISTS cap_currency_code character varying(3) NOT NULL DEFAULT 'AED';

ALTER TABLE public.mcc_sector_map
    ADD COLUMN IF NOT EXISTS country_code character varying(2) NOT NULL DEFAULT 'AE';

ALTER TABLE public.scheme_fee_rate
    ADD COLUMN IF NOT EXISTS country_code character varying(2) NOT NULL DEFAULT 'AE';

ALTER TABLE public.tenant
    ADD COLUMN IF NOT EXISTS home_country_code character varying(2) NOT NULL DEFAULT 'AE';

-- ── 4. Missing indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_interchange_rate_local_generic
    ON public.interchange_rate_local USING btree (tenant_id, dest) WHERE (mcc IS NULL);
CREATE INDEX IF NOT EXISTS idx_interchange_rate_local_c_mcc
    ON public.interchange_rate_local USING btree (country_code, mcc) WHERE (mcc IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_interchange_rate_local_c_generic
    ON public.interchange_rate_local USING btree (country_code, dest) WHERE (mcc IS NULL);
CREATE INDEX IF NOT EXISTS idx_interchange_rate_local_c_lookup
    ON public.interchange_rate_local USING btree (country_code, dest, priority DESC);
CREATE INDEX IF NOT EXISTS idx_mcc_sector_map_country
    ON public.mcc_sector_map USING btree (country_code, mcc);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mcc_sector_map_key
    ON public.mcc_sector_map USING btree (country_code, COALESCE(tenant_id, 0), mcc);
CREATE INDEX IF NOT EXISTS idx_scheme_fee_rate_country
    ON public.scheme_fee_rate USING btree (country_code, dest, channel);

-- ── 5. Missing foreign keys to ref_country ───────────────────────────
-- Safe to validate immediately: the columns were just added with DEFAULT
-- 'AE', and the 'AE' row was seeded in step 1.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_interchange_rate_local_country'
                     AND conrelid = 'public.interchange_rate_local'::regclass) THEN
        ALTER TABLE public.interchange_rate_local
            ADD CONSTRAINT fk_interchange_rate_local_country
            FOREIGN KEY (country_code) REFERENCES public.ref_country(country_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_mcc_sector_map_country'
                     AND conrelid = 'public.mcc_sector_map'::regclass) THEN
        ALTER TABLE public.mcc_sector_map
            ADD CONSTRAINT fk_mcc_sector_map_country
            FOREIGN KEY (country_code) REFERENCES public.ref_country(country_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_scheme_fee_rate_country'
                     AND conrelid = 'public.scheme_fee_rate'::regclass) THEN
        ALTER TABLE public.scheme_fee_rate
            ADD CONSTRAINT fk_scheme_fee_rate_country
            FOREIGN KEY (country_code) REFERENCES public.ref_country(country_code);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'fk_tenant_home_country'
                     AND conrelid = 'public.tenant'::regclass) THEN
        ALTER TABLE public.tenant
            ADD CONSTRAINT fk_tenant_home_country
            FOREIGN KEY (home_country_code) REFERENCES public.ref_country(country_code);
    END IF;
END $$;

-- ── 6. Definition changes ────────────────────────────────────────────

-- 6a. tenant_id must allow NULL: country-level default pricing rows have
--     no tenant. The COALESCE(tenant_id, 0) unique indexes above keep
--     per-tenant vs global rows from colliding.
ALTER TABLE public.interchange_rate_local ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE public.mcc_sector_map        ALTER COLUMN tenant_id DROP NOT NULL;
ALTER TABLE public.scheme_fee_rate       ALTER COLUMN tenant_id DROP NOT NULL;

-- 6b. Replace old unique keys with the country-aware versions.
--     mcc_sector_map: old UNIQUE (tenant_id, mcc) would block the same MCC
--     for two countries; uq_mcc_sector_map_key (created above) replaces it.
ALTER TABLE public.mcc_sector_map DROP CONSTRAINT IF EXISTS mcc_sector_map_tenant_id_mcc_key;

--     scheme_fee_rate: same index NAME exists in prod with the OLD column
--     list (tenant_id, dest, channel, scheme_group). Drop only if it is
--     still the old definition, then create the country-aware one.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_indexes
               WHERE schemaname = 'public' AND indexname = 'uq_scheme_fee_rate_key'
                 AND indexdef NOT LIKE '%country_code%') THEN
        DROP INDEX public.uq_scheme_fee_rate_key;
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uq_scheme_fee_rate_key
    ON public.scheme_fee_rate USING btree (country_code, COALESCE(tenant_id, 0), dest, channel, COALESCE(scheme_group, ''::character varying));

-- 6c. users.email relaxed to match dev: nullable, no unique constraint
--     (username stays the unique login key). REVIEW: this REMOVES the
--     email uniqueness guarantee in prod — intentional in dev's schema.
ALTER TABLE public.users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS uq_users_email;

COMMIT;

-- Post-check (run separately, should all return the new objects):
--   SELECT COUNT(*) FROM public.ecom_flat_fee;                                -- table exists
--   SELECT column_name FROM information_schema.columns
--    WHERE table_name='tenant' AND column_name='home_country_code';           -- column exists
--   SELECT conname FROM pg_constraint WHERE conname LIKE 'fk_%_country';      -- FKs exist
