spring.application.name=acquira-system

# Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/postgres?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.sql.init.mode=always

# Batch Configuration
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Logging
logging.level.com.acquira=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.batch=INFO
logging.file.name=logs/acquira.log

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
