-- V2026_09_15_01: Bahrain Visa domestic alignment to the Visa Domestic IRF Guide
-- (Bahrain Supplemental Requirements, effective 25 Jan 2025).
--
-- What this does:
--   A) Seeds ref_bin_product_tier with Visa product codes (A/F/P/... -> VCLAS/VGOLD/...).
--      Until now the table held only Mastercard codes, so every BH Visa txn fell
--      through to the flat 1.75/1.90 tier-wildcard default.
--   B) Inserts BH Visa product-tier rate rows at priority 20:
--      POS = manual Product Rate, ECOM = manual Alternative Rate (product +0.20%).
--      The existing priority-15 flat rows are KEPT as last resort for unmapped BINs;
--      sector MCC rows at priority 40/60 still win (ORDER BY priority DESC).
--   C) Fixes: MCC 8220 to Education 0.85%; auto dealers 5511/5521 cap at USD 150
--      (56.40 BHD at the 0.376 peg - engine caps in store base currency);
--      deletes the redundant per-MCC Visa rows that sat at the default 1.75/1.90.
--
-- Deliberate decisions (flagged for business sign-off):
--   * J3 (prepaid) priced as Classic - the manual has no prepaid product line.
--   * I1 (Infinite Privilege) priced as Infinite.
--   * Codes with no manual treatment (L Electron, Q private label, M, V, X, E, R)
--     are NOT seeded - they fall to the flat priority-15 fallback.
--   * Acquirer-downgrade ladder (+0.25%) not modeled - no downgrade signal in feed.
--
-- Guarded on schema_migration_log per the ledger convention: re-runs are no-ops.

-- ---------------------------------------------------------------------------
-- A) Visa product code -> tier seeds (shared table; 1-2 char Visa codes cannot
--    collide with 3-char MC codes). Tier labels <= 10 chars (card_tier limit).
-- ---------------------------------------------------------------------------
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'A','VCLAS','CONSUMER','Visa Traditional -> Classic 1.25' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'F','VCLAS','CONSUMER','Visa Classic 1.25' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'J3','VCLAS','CONSUMER','Visa prepaid -> Classic treatment (no prepaid line in BH manual)' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'P','VGOLD','CONSUMER','Visa Gold 1.40' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'B','VRWD','CONSUMER','Visa Traditional Rewards -> Rewards 1.70' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'N1','VRWD','CONSUMER','Visa Rewards 1.70' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'N','VPLAT','CONSUMER','Visa Platinum 1.85' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'C','VSIG','CONSUMER','Visa Signature 2.05' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'I','VINF','CONSUMER','Visa Infinite 2.10' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'I1','VINF','CONSUMER','Visa Infinite Privilege -> Infinite (no Privilege line in BH manual)' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'I2','VUHNW','CONSUMER','Visa UHNW 2.30' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'G','VBUS','COMMERCIAL','Visa Business 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'G3','VBUS','COMMERCIAL','Visa Business Enhanced -> Business 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'G5','VBUS','COMMERCIAL','Visa Business Rewards -> Business 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'G1','VBUSSIG','COMMERCIAL','Visa Signature Business 2.10' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'G4','VBUSINF','COMMERCIAL','Visa Infinite Business 2.15' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'K','VCORP','COMMERCIAL','Visa Corporate 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'K1','VCORP','COMMERCIAL','Visa GSA Corporate -> Corporate 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'S','VPUR','COMMERCIAL','Visa Purchasing 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'S1','VPUR','COMMERCIAL','Visa Fleet -> Purchasing 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'S2','VPUR','COMMERCIAL','Visa Purchasing w/ fleet -> Purchasing 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;
INSERT INTO ref_bin_product_tier (product_code, card_tier, card_class, note) SELECT 'S6','VPUR','COMMERCIAL','Visa Purchasing variant -> Purchasing 2.00' WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (product_code) DO NOTHING;

-- ---------------------------------------------------------------------------
-- B) BH Visa product-tier rate rows, priority 20 (beats the 15 flat fallback,
--    loses to sector MCC rows at 40/60 - matching the manual's hierarchy where
--    industry fee programs precede product rate). card_type stays NULL: the BH
--    manual prices by product regardless of funding source (F is 84% debit and
--    must still get Classic 1.25).
--    POS = Product Rate; ECOM = Alternative Rate (product +0.20).
-- ---------------------------------------------------------------------------
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VCLAS',NULL,0.012500,NULL,'BH Visa Classic POS 1.25 (manual product rate)',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VCLAS',NULL,0.014500,NULL,'BH Visa Classic ECOM 1.45 (manual alternative rate)',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VGOLD',NULL,0.014000,NULL,'BH Visa Gold POS 1.40',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VGOLD',NULL,0.016000,NULL,'BH Visa Gold ECOM 1.60',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VRWD',NULL,0.017000,NULL,'BH Visa Rewards POS 1.70',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VRWD',NULL,0.019000,NULL,'BH Visa Rewards ECOM 1.90',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VPLAT',NULL,0.018500,NULL,'BH Visa Platinum POS 1.85',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VPLAT',NULL,0.020500,NULL,'BH Visa Platinum ECOM 2.05',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VSIG',NULL,0.020500,NULL,'BH Visa Signature POS 2.05',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VSIG',NULL,0.022500,NULL,'BH Visa Signature ECOM 2.25',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VINF',NULL,0.021000,NULL,'BH Visa Infinite POS 2.10',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VINF',NULL,0.023000,NULL,'BH Visa Infinite ECOM 2.30',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VUHNW',NULL,0.023000,NULL,'BH Visa UHNW POS 2.30',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VUHNW',NULL,0.025000,NULL,'BH Visa UHNW ECOM 2.50',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VBUS',NULL,0.020000,NULL,'BH Visa Business POS 2.00',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VBUS',NULL,0.022000,NULL,'BH Visa Business ECOM 2.20',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VCORP',NULL,0.020000,NULL,'BH Visa Corporate POS 2.00',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VCORP',NULL,0.022000,NULL,'BH Visa Corporate ECOM 2.20',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VPUR',NULL,0.020000,NULL,'BH Visa Purchasing POS 2.00',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VPUR',NULL,0.022000,NULL,'BH Visa Purchasing ECOM 2.20',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VBUSSIG',NULL,0.021000,NULL,'BH Visa Signature Business POS 2.10',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VBUSSIG',NULL,0.023000,NULL,'BH Visa Signature Business ECOM 2.30',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','POS','Visa',NULL,'VBUSINF',NULL,0.021500,NULL,'BH Visa Infinite Business POS 2.15',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');
INSERT INTO interchange_rate_local (tenant_id,priority,dest,channel,scheme_group,card_type,tier,mcc_sector,interchange_pct,cap_amount,label,mcc,country_code,cap_currency_code,flat_fee,rate_status,effective_from,effective_to,source_note,min_ticket,max_ticket) SELECT NULL,20,'DOMESTIC','ECOM','Visa',NULL,'VBUSINF',NULL,0.023500,NULL,'BH Visa Infinite Business ECOM 2.35',NULL,'BH','BHD',0.0000,'APPROVED',NULL,NULL,'Visa BH IRF Guide 2025-01-25 s5.1',NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');

-- ---------------------------------------------------------------------------
-- C) Sector fixes + cleanup
-- ---------------------------------------------------------------------------
-- C1: MCC 8220 (colleges/universities) is Education 0.85% in the manual, was 0.75%.
UPDATE interchange_rate_local SET interchange_pct = 0.008500,
       label = 'BH Visa ' || channel || ' MCC 8220 (Education 0.85, fixed from 0.75)'
WHERE country_code='BH' AND scheme_group='Visa' AND mcc='8220' AND interchange_pct = 0.007500
  AND NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');

-- C2: Auto dealers 5511/5521 - manual caps consumer auto at USD 150.
--     Engine caps in store base currency (BHD): 150 USD * 0.376 = 56.40 BHD.
UPDATE interchange_rate_local SET cap_amount = 56.4000, cap_currency_code = 'BHD',
       label = label || ' cap USD150=56.40BHD'
WHERE country_code='BH' AND scheme_group='Visa' AND mcc IN ('5511','5521')
  AND interchange_pct = 0.012000 AND cap_amount IS NULL
  AND NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');

-- C3: Drop the redundant per-MCC Visa rows that sat at the flat default rate
--     (they added nothing over the priority-15 default and now would mask tiers
--     for those MCCs, since priority 60 beats the new tier rows at 20).
DELETE FROM interchange_rate_local
WHERE country_code='BH' AND scheme_group='Visa' AND priority=60 AND mcc IS NOT NULL
  AND interchange_pct IN (0.017500, 0.019000)
  AND NOT EXISTS (SELECT 1 FROM schema_migration_log WHERE filename='V2026_09_15_01__visa_bh_manual_align.sql');

-- Verify: expect 24 tier rows, 8220 at 0.85, 5511/5521 capped, 0 default-rate MCC rows
SELECT 'tier_rows' AS check, COUNT(*) FROM interchange_rate_local
WHERE country_code='BH' AND scheme_group='Visa' AND priority=20 AND tier LIKE 'V%'
UNION ALL
SELECT 'mcc8220_at_085', COUNT(*) FROM interchange_rate_local
WHERE country_code='BH' AND scheme_group='Visa' AND mcc='8220' AND interchange_pct=0.008500
UNION ALL
SELECT 'auto_capped', COUNT(*) FROM interchange_rate_local
WHERE country_code='BH' AND scheme_group='Visa' AND mcc IN ('5511','5521') AND cap_amount=56.4000
UNION ALL
SELECT 'redundant_left', COUNT(*) FROM interchange_rate_local
WHERE country_code='BH' AND scheme_group='Visa' AND priority=60 AND mcc IS NOT NULL
  AND interchange_pct IN (0.017500, 0.019000);

INSERT INTO schema_migration_log (filename) VALUES ('V2026_09_15_01__visa_bh_manual_align.sql') ON CONFLICT (filename) DO NOTHING;
