-- UAE (tenant_id = 1) — Sales TL mapping, generated 2026-09-11
-- Source: TL Tagging Latest.xlsx + Internal-User-list (2).xlsx (joined on email)
-- Idempotent: safe to re-run; re-running moves agents if leads changed.
-- Order per docs/RM_TEAM_MERCHANT_MAPPING_GUIDE.md

BEGIN;

-- Step 0: wipe existing tenant-1 team structure (fresh load)
-- assignments first (FK to sales_team_mapping), then leads.
-- Profiles are kept (they carry targets/notes) — names are overwritten below.
DELETE FROM sales_user_assignment WHERE tenant_id = 1;
DELETE FROM sales_team_mapping    WHERE tenant_id = 1;

-- Step 1: ensure agent profile rows exist for every mapped SID
INSERT INTO sales_agent_profile (tenant_id, sales_user_id, sales_email, status, created_at, updated_at)
VALUES
    (1, '6064', 'abhishek.yadav@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6206', 'alaa.alkhder@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6238', 'alia.ayoub@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6280', 'hina_azhar442@gmail.com', 'ACTIVE', NOW(), NOW()),
    (1, '6162', 'imran.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '2900', 'prasad.gajendiran@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6070', 'prasadraja07@yahoo.com', 'ACTIVE', NOW(), NOW()),
    (1, '6258', 'ghassan.mardini@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6398', 'abdelrahman.moustafa@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6033', 'afsal.muhammed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6075', 'jaafar.marhoon@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6271', 'zubair.mustafa@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6326', 'beentuafsary@apexpos.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6159', 'ashfaq.ahmed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6300', 'mohammed.salman@comerapay.com', 'ACTIVE', NOW(), NOW()),
    (1, '6301', 'abdul.khader@comeramoney.com', 'ACTIVE', NOW(), NOW()),
    (1, '6266', 'sales.support@gipsp.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6346', 'chary.patrimonio@mawarid.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6345', 'pater.paul@mawarid.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6391', 'preethi.s@fgfme.com', 'ACTIVE', NOW(), NOW()),
    (1, '6287', 'office@paymint.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6286', 'faisal.arif@paymint.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6423', 'michelle.r@paynovame.com', 'ACTIVE', NOW(), NOW()),
    (1, '6452', 'gokul.kumar@smoothpay.ai', 'ACTIVE', NOW(), NOW()),
    (1, '6458', 'harsha.vardhini@smoothpay.ai', 'ACTIVE', NOW(), NOW()),
    (1, '6404', 'zahra@swiftpay.ae', 'ACTIVE', NOW(), NOW()),
    (1, '6298', 'debbie@yallapayments.com', 'ACTIVE', NOW(), NOW()),
    (1, '6373', 'shamsana@yallapayments.com', 'ACTIVE', NOW(), NOW()),
    (1, '6369', 'abdallah.fayed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6339', 'ariz.zafar@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6366', 'quler.christy@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6382', 'farhan.ali@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6367', 'fayis.ismayil@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6372', 'ghazia.rukhsar@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6283', 'mohamed.hamdi@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6354', 'ishan.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6375', 'jawed.eqbal@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6337', 'mahmoud.abdelfatah@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6394', 'mahmoud.aly@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6270', 'maqbul.ahmed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6275', 'mohammed.fareed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6276', 'muhammad.idrees@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6474', 'muhammadyawar.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6390', 'nirankar.yadav@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6340', 'noor.sheikh@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6241', 'raamish.zaidi@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6368', 'rajesh.unnikrishnan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6302', 'ramy.alaa@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6353', 'saira.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6274', 'salman.ghani@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6393', 'sankar.veeramani@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6362', 'shaikziaul.haque@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6281', 'shiji.thomas@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6381', 'zeshan.afzal@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6447', 'abbas.syed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6464', 'angelina.benjamin@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6352', 'anwarali.shaik@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6438', 'harsha.ailani@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6433', 'imran.ali@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6446', 'jai.gopal@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6444', 'karim.shaikh@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6460', 'keshav.gupta@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6439', 'krishnanunni.vattamanna@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6453', 'mohammad.akram@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6443', 'mohammadmazhar.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6436', 'qadir.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6468', 'sarfaraz.ali@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6418', 'urwa.sheikh@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6455', 'vivek.singh@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6374', 'ahmed.abdalla@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6320', 'ahmedadel.ibrahim@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6318', 'akram.amirouche@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6396', 'aylar.atdayeva@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6385', 'bahaaeldin.abdelsalam@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6395', 'fahad.rifaqat@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6327', 'muhammad.faheem@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6387', 'imtiaz.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6386', 'islam.nasser@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6303', 'kaushik.vyas@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6400', 'manu.mohan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6333', 'meraj.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6342', 'mian.ali@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6328', 'mohammed.mumin@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6380', 'rohit.sharma@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6370', 'rohma.irfan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6243', 'shabil.sivanandan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6388', 'shuja.azeem@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6361', 'tajammul.syed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6384', 'thiyagarajan.muthurakku@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6321', 'vikas.rai@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6365', 'vivek.choudhary@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6336', 'abdelfattah.youssef@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6399', 'zohaib.sultan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6435', 'abdur.rafay@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6461', 'apple.diaz@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6414', 'feroz.hyder@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6401', 'gulam.idris@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6425', 'javeed.mohammed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6402', 'jemis.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6473', 'mahmoud.amer@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6426', 'mohammad.talha@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6432', 'muhammadhassan.siddiqui@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6454', 'muhammad.moeed@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6430', 'muhammed.uvais@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6427', 'naved.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6406', 'prabakaran.balasundaram@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6249', 'rehmanali.butt@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6462', 'sadam.rabi@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6437', 'sajeeth.kumar@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6431', 'syed.danish@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6412', 'tariq.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6413', 'zaif.george@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6463', 'zakaullah.butt@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6471', 'abdelrahman.farrag@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6424', 'amjad.hassan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6055', 'layla.alalwan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6405', 'meraj.hussain@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6329', 'rawan.alalool@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6158', 'rizwan.khan@afs.com.bh', 'ACTIVE', NOW(), NOW()),
    (1, '6445', 'varun.thekkumbadan@afs.com.bh', 'ACTIVE', NOW(), NOW())
ON CONFLICT (tenant_id, sales_user_id) DO NOTHING;

-- Step 2: team leads (keyed by email; re-run updates name)
INSERT INTO sales_team_mapping (tenant_id, team_lead_name, team_lead_email, is_default)
VALUES
    (1, 'Rizwan Khan', 'rizwan.khan@afs.com.bh', false),
    (1, 'Ashfaq Ahmed', 'ashfaq.ahmed@afs.com.bh', false),
    (1, 'Maqbul Ahmed', 'maqbul.ahmed@afs.com.bh', false),
    (1, 'Rehman Ali Butt', 'rehmanali.butt@afs.com.bh', false),
    (1, 'Mohammed Mumin', 'mohammed.mumin@afs.com.bh', false),
    (1, 'Mohamed Anwar', 'mohamed.anwar@afs.com.bh', false),
    (1, 'AFS Test', 'afs.test@afs.com.bh', false),
    (1, 'Vacant', 'vacant@afs.com.bh', true)
ON CONFLICT (tenant_id, team_lead_email)
DO UPDATE SET team_lead_name = EXCLUDED.team_lead_name;

-- Step 3: assign agents (SID -> team lead), upsert moves on re-run
INSERT INTO sales_user_assignment (tenant_id, sales_user_id, team_lead_id, assigned_at)
SELECT 1, v.sid, m.id, NOW()
FROM (VALUES
    ('6064', 'afs.test@afs.com.bh'),
    ('6206', 'afs.test@afs.com.bh'),
    ('6238', 'afs.test@afs.com.bh'),
    ('6280', 'afs.test@afs.com.bh'),
    ('6162', 'afs.test@afs.com.bh'),
    ('2900', 'afs.test@afs.com.bh'),
    ('6070', 'afs.test@afs.com.bh'),
    ('6258', 'afs.test@afs.com.bh'),
    ('6398', 'afs.test@afs.com.bh'),
    ('6033', 'afs.test@afs.com.bh'),
    ('6075', 'afs.test@afs.com.bh'),
    ('6271', 'afs.test@afs.com.bh'),
    ('6326', 'ashfaq.ahmed@afs.com.bh'),
    ('6159', 'ashfaq.ahmed@afs.com.bh'),
    ('6300', 'ashfaq.ahmed@afs.com.bh'),
    ('6301', 'ashfaq.ahmed@afs.com.bh'),
    ('6266', 'ashfaq.ahmed@afs.com.bh'),
    ('6346', 'ashfaq.ahmed@afs.com.bh'),
    ('6345', 'ashfaq.ahmed@afs.com.bh'),
    ('6391', 'ashfaq.ahmed@afs.com.bh'),
    ('6287', 'ashfaq.ahmed@afs.com.bh'),
    ('6286', 'ashfaq.ahmed@afs.com.bh'),
    ('6423', 'ashfaq.ahmed@afs.com.bh'),
    ('6452', 'ashfaq.ahmed@afs.com.bh'),
    ('6458', 'ashfaq.ahmed@afs.com.bh'),
    ('6404', 'ashfaq.ahmed@afs.com.bh'),
    ('6298', 'ashfaq.ahmed@afs.com.bh'),
    ('6373', 'ashfaq.ahmed@afs.com.bh'),
    ('6369', 'maqbul.ahmed@afs.com.bh'),
    ('6339', 'maqbul.ahmed@afs.com.bh'),
    ('6366', 'maqbul.ahmed@afs.com.bh'),
    ('6382', 'maqbul.ahmed@afs.com.bh'),
    ('6367', 'maqbul.ahmed@afs.com.bh'),
    ('6372', 'maqbul.ahmed@afs.com.bh'),
    ('6283', 'maqbul.ahmed@afs.com.bh'),
    ('6354', 'maqbul.ahmed@afs.com.bh'),
    ('6375', 'maqbul.ahmed@afs.com.bh'),
    ('6337', 'maqbul.ahmed@afs.com.bh'),
    ('6394', 'maqbul.ahmed@afs.com.bh'),
    ('6270', 'maqbul.ahmed@afs.com.bh'),
    ('6275', 'maqbul.ahmed@afs.com.bh'),
    ('6276', 'maqbul.ahmed@afs.com.bh'),
    ('6474', 'maqbul.ahmed@afs.com.bh'),
    ('6390', 'maqbul.ahmed@afs.com.bh'),
    ('6340', 'maqbul.ahmed@afs.com.bh'),
    ('6241', 'maqbul.ahmed@afs.com.bh'),
    ('6368', 'maqbul.ahmed@afs.com.bh'),
    ('6302', 'maqbul.ahmed@afs.com.bh'),
    ('6353', 'maqbul.ahmed@afs.com.bh'),
    ('6274', 'maqbul.ahmed@afs.com.bh'),
    ('6393', 'maqbul.ahmed@afs.com.bh'),
    ('6362', 'maqbul.ahmed@afs.com.bh'),
    ('6281', 'maqbul.ahmed@afs.com.bh'),
    ('6381', 'maqbul.ahmed@afs.com.bh'),
    ('6447', 'mohamed.anwar@afs.com.bh'),
    ('6464', 'mohamed.anwar@afs.com.bh'),
    ('6352', 'mohamed.anwar@afs.com.bh'),
    ('6438', 'mohamed.anwar@afs.com.bh'),
    ('6433', 'mohamed.anwar@afs.com.bh'),
    ('6446', 'mohamed.anwar@afs.com.bh'),
    ('6444', 'mohamed.anwar@afs.com.bh'),
    ('6460', 'mohamed.anwar@afs.com.bh'),
    ('6439', 'mohamed.anwar@afs.com.bh'),
    ('6453', 'mohamed.anwar@afs.com.bh'),
    ('6443', 'mohamed.anwar@afs.com.bh'),
    ('6436', 'mohamed.anwar@afs.com.bh'),
    ('6468', 'mohamed.anwar@afs.com.bh'),
    ('6418', 'mohamed.anwar@afs.com.bh'),
    ('6455', 'mohamed.anwar@afs.com.bh'),
    ('6374', 'mohammed.mumin@afs.com.bh'),
    ('6320', 'mohammed.mumin@afs.com.bh'),
    ('6318', 'mohammed.mumin@afs.com.bh'),
    ('6396', 'mohammed.mumin@afs.com.bh'),
    ('6385', 'mohammed.mumin@afs.com.bh'),
    ('6395', 'mohammed.mumin@afs.com.bh'),
    ('6327', 'mohammed.mumin@afs.com.bh'),
    ('6387', 'mohammed.mumin@afs.com.bh'),
    ('6386', 'mohammed.mumin@afs.com.bh'),
    ('6303', 'mohammed.mumin@afs.com.bh'),
    ('6400', 'mohammed.mumin@afs.com.bh'),
    ('6333', 'mohammed.mumin@afs.com.bh'),
    ('6342', 'mohammed.mumin@afs.com.bh'),
    ('6328', 'mohammed.mumin@afs.com.bh'),
    ('6380', 'mohammed.mumin@afs.com.bh'),
    ('6370', 'mohammed.mumin@afs.com.bh'),
    ('6243', 'mohammed.mumin@afs.com.bh'),
    ('6388', 'mohammed.mumin@afs.com.bh'),
    ('6361', 'mohammed.mumin@afs.com.bh'),
    ('6384', 'mohammed.mumin@afs.com.bh'),
    ('6321', 'mohammed.mumin@afs.com.bh'),
    ('6365', 'mohammed.mumin@afs.com.bh'),
    ('6336', 'mohammed.mumin@afs.com.bh'),
    ('6399', 'mohammed.mumin@afs.com.bh'),
    ('6435', 'rehmanali.butt@afs.com.bh'),
    ('6461', 'rehmanali.butt@afs.com.bh'),
    ('6414', 'rehmanali.butt@afs.com.bh'),
    ('6401', 'rehmanali.butt@afs.com.bh'),
    ('6425', 'rehmanali.butt@afs.com.bh'),
    ('6402', 'rehmanali.butt@afs.com.bh'),
    ('6473', 'rehmanali.butt@afs.com.bh'),
    ('6426', 'rehmanali.butt@afs.com.bh'),
    ('6432', 'rehmanali.butt@afs.com.bh'),
    ('6454', 'rehmanali.butt@afs.com.bh'),
    ('6430', 'rehmanali.butt@afs.com.bh'),
    ('6427', 'rehmanali.butt@afs.com.bh'),
    ('6406', 'rehmanali.butt@afs.com.bh'),
    ('6249', 'rehmanali.butt@afs.com.bh'),
    ('6462', 'rehmanali.butt@afs.com.bh'),
    ('6437', 'rehmanali.butt@afs.com.bh'),
    ('6431', 'rehmanali.butt@afs.com.bh'),
    ('6412', 'rehmanali.butt@afs.com.bh'),
    ('6413', 'rehmanali.butt@afs.com.bh'),
    ('6463', 'rehmanali.butt@afs.com.bh'),
    ('6471', 'rizwan.khan@afs.com.bh'),
    ('6424', 'rizwan.khan@afs.com.bh'),
    ('6055', 'rizwan.khan@afs.com.bh'),
    ('6405', 'rizwan.khan@afs.com.bh'),
    ('6329', 'rizwan.khan@afs.com.bh'),
    ('6158', 'rizwan.khan@afs.com.bh'),
    ('6445', 'rizwan.khan@afs.com.bh')
) AS v(sid, lead_email)
JOIN sales_team_mapping m
  ON m.tenant_id = 1 AND m.team_lead_email = v.lead_email
ON CONFLICT (tenant_id, sales_user_id)
DO UPDATE SET team_lead_id = EXCLUDED.team_lead_id, assigned_at = NOW();

-- Step 4: display names
UPDATE sales_agent_profile p
SET display_name = v.name, updated_at = NOW()
FROM (VALUES
    ('6064', 'Abhishek Yadav'),
    ('6206', 'Alaa Alkhder'),
    ('6238', 'Alia Ayoub'),
    ('6280', 'Hina Azhar'),
    ('6162', 'Imran Khan'),
    ('2900', 'IT Test'),
    ('6070', 'IT Test'),
    ('6258', 'IT Test'),
    ('6398', 'IT Test'),
    ('6033', 'IT Test'),
    ('6075', 'Jaafar Marhoon'),
    ('6271', 'Zubair Mustafa'),
    ('6326', 'APEX POS PAYMENT SERVICES PROVIDER'),
    ('6159', 'Ashfaq Ahmed'),
    ('6300', 'COMERA PAY LLC'),
    ('6301', 'COMERA PAY LLC'),
    ('6266', 'GAMA INTERNATIONAL PAYMENT SERVICES PROVIDER'),
    ('6346', 'Mawarid Finance'),
    ('6345', 'Mawarid Finance'),
    ('6391', 'PAY FGF LLC FZ'),
    ('6287', 'PAYMINT ELECTRONIC CARDS LLC'),
    ('6286', 'PAYMINT ELECTRONIC CARDS LLC'),
    ('6423', 'Paynova Electronic Cards Trading LLC'),
    ('6452', 'Smooth Innovations Technology LLC'),
    ('6458', 'Smooth Innovations Technology LLC'),
    ('6404', 'SWIFTPAY PAYMENT SERVICES PROVIDER CO. L.L.C'),
    ('6298', 'YALLA SAREEA COMPUTERS'),
    ('6373', 'YALLA SAREEA COMPUTERS'),
    ('6369', 'Abdallah Fayed'),
    ('6339', 'Ariz Zafar'),
    ('6366', 'Christy Quler'),
    ('6382', 'Farhan Ali'),
    ('6367', 'Fayis Ismayil'),
    ('6372', 'Ghazia Rukhsar'),
    ('6283', 'Hamdi Mohamed'),
    ('6354', 'Ishan Khan'),
    ('6375', 'Jawed Eqbal'),
    ('6337', 'Mahmoud AbdelFatah'),
    ('6394', 'Mahmoud Aly'),
    ('6270', 'Maqbul Ahmed'),
    ('6275', 'Mohammed Fareed'),
    ('6276', 'Muhammad Idrees'),
    ('6474', 'Muhammad Yawar'),
    ('6390', 'Nirankar Yadav'),
    ('6340', 'Noor Sheikh'),
    ('6241', 'Raamish Zaidi'),
    ('6368', 'Rajesh Unnikrishnan'),
    ('6302', 'Ramy Alaa'),
    ('6353', 'Saira Khan'),
    ('6274', 'Salman Ghani'),
    ('6393', 'Sankar Veeramani'),
    ('6362', 'Shaik Ziaul Haque'),
    ('6281', 'Shiji Thomas'),
    ('6381', 'Zeeshan Afzal'),
    ('6447', 'Abbas Syed'),
    ('6464', 'Angelina Benjamin'),
    ('6352', 'Anwarali Shaik'),
    ('6438', 'Harsha Ailani'),
    ('6433', 'Imran Ali'),
    ('6446', 'Jai Gopal'),
    ('6444', 'Karim Shaikh'),
    ('6460', 'Keshav Gupta'),
    ('6439', 'Krishanan Unni'),
    ('6453', 'Mohammad Akram'),
    ('6443', 'Mohammad Mazhar Khan'),
    ('6436', 'Qadir Khan'),
    ('6468', 'Sarfaraz Ali'),
    ('6418', 'Urwa Sheikh'),
    ('6455', 'Vivek Singh'),
    ('6374', 'Ahmed Abdalla'),
    ('6320', 'Ahmed Ibrahim'),
    ('6318', 'Akram Amirouche'),
    ('6396', 'Aylar Atdayeva'),
    ('6385', 'Bahaaeldin Abdelsalam'),
    ('6395', 'Fahad Rifaqat'),
    ('6327', 'Faheem Muhammad'),
    ('6387', 'Imtiaz Khan'),
    ('6386', 'Islam Nasser'),
    ('6303', 'Kaushik Vyas'),
    ('6400', 'Manu Mohan'),
    ('6333', 'Meraj Khan'),
    ('6342', 'Mian Ali'),
    ('6328', 'Mumin Mohammed'),
    ('6380', 'Rohit Sharma'),
    ('6370', 'Rohma Irfan'),
    ('6243', 'Shabil Sivanandan'),
    ('6388', 'Shuja Azeem'),
    ('6361', 'Tajammul Syed'),
    ('6384', 'Thiyagarajan Muthurakku'),
    ('6321', 'Vikas Rai'),
    ('6365', 'Vivek Choudhary'),
    ('6336', 'Youssef Abdelfattah'),
    ('6399', 'Zohaib Sultan'),
    ('6435', 'Abdur Rafay'),
    ('6461', 'Apple Diaz'),
    ('6414', 'Feroz Hyder'),
    ('6401', 'Gulam Idris'),
    ('6425', 'Javeed Mohammed'),
    ('6402', 'Jemis Khan'),
    ('6473', 'Mahmoud Amer'),
    ('6426', 'Mohammad Talha'),
    ('6432', 'Muhammad Hassan Siddiqui'),
    ('6454', 'Muhammad Moeed'),
    ('6430', 'Muhammed Uvais'),
    ('6427', 'Naved Khan'),
    ('6406', 'Prabakaran Balasundaram'),
    ('6249', 'Rehmanali Butt'),
    ('6462', 'Sadam Rabi'),
    ('6437', 'Sajeeth Kumar'),
    ('6431', 'Syed Danish'),
    ('6412', 'Tariq Khan'),
    ('6413', 'Zaif George'),
    ('6463', 'Zakaullah Butt'),
    ('6471', 'Abdelrahman Farrag'),
    ('6424', 'Amjad Hassan'),
    ('6055', 'Layla Alalwan'),
    ('6405', 'Meraj Hussain'),
    ('6329', 'Rawan Alalool'),
    ('6158', 'Rizwan Khan'),
    ('6445', 'Varun Thekkumbadan')
) AS v(sid, name)
WHERE p.sales_user_id = v.sid
  AND p.tenant_id = 1;

COMMIT;

-- Verify: agent -> name -> team with merchant counts
SELECT p.sales_user_id, p.display_name, p.sales_email,
       m.team_lead_name,
       (SELECT COUNT(*) FROM dim_merchant dm
         WHERE dm.tenant_id = p.tenant_id AND dm.sales_user_id = p.sales_user_id) AS merchant_count
FROM sales_agent_profile p
LEFT JOIN sales_user_assignment a ON a.tenant_id = p.tenant_id AND a.sales_user_id = p.sales_user_id
LEFT JOIN sales_team_mapping m ON m.id = a.team_lead_id
WHERE p.tenant_id = 1
ORDER BY m.team_lead_name NULLS LAST, p.display_name;
